audit/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/clearcache',include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('installation/',include('installation.urls')),
    path('', include('panel.urls')),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]

urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

handler400 ='errors.views.error_400'
handler403 ='errors.views.error_403'
handler404 ='errors.views.error_404'
handler500='errors.views.error_500'

panel/urls.py
from django.urls import path
from django import views
from . import views
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns=[
    path('',Home.as_view(),name='home'),
    path('energy/consuption',weeklyConsuption.as_view(),name='weekly consuption'),
    path('cost/calculator',costCalculator.as_view(),name='cost calculator'),
    path('accounts/login/',Login.as_view(),name='login'),
    path('dashboard',Dashboard.as_view(),name='dashboard'),
    path('accounts/logout',views.user_logout,name='logout'),
    path('accounts/reset/password',auth_views.PasswordResetView.as_view(form_class=UserResetPassword,extra_context={'title':'Password Reset'},template_name='panel/password_reset.html'),{'title':'Password Reset'},name='password_reset'),
    path('accounts/reset/password/done',auth_views.PasswordResetDoneView.as_view(template_name='panel/password_reset_done.html'),name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='panel/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/password/success',auth_views.PasswordResetCompleteView.as_view(template_name='panel/password_reset_complete.html'),name='password_reset_complete'),
    path('<str:username>',ProfileView.as_view(),name='profile'),
    path('change/profile/pic',views.profilePic,name='profile pic'),
    path('edit/social/links',views.edit_social_link,name='edit social link'),
    path('password/change',views.passwordChange,name='password change'),
    path('site/contact',views.siteContact,name='site contact'),
    path('site/social/links/settings',views.siteSocial,name='site social links'),
    path('add/meter/',views.addMeter,name='add meter'),
    path('edit/meter/<int:id>',EditMeter.as_view(),name='edit meter'),
    path('delete/meter/<int:id>',views.deleteMeter,name='delete meter'),
    path('add/equipment/',views.addEquipment,name='add equipment'),
    path('meters/',views.meters,name='meters'),
    path('icdc/equipments/',views.equipments,name='equipments'),
    path('edit/equipment/<int:id>',EditEquipment.as_view(),name='edit equipment'),
    path('delete/equipment/<int:id>',views.deleteEquipment,name='delete equipment'),
    #home updater
    path('home/updater',views.homeUpdater,name='home updater'),
    path('view/meter/<int:id>',views.openMeter,name='view meter'),
    path('meter/reading/costs',costCalculatorReading.as_view(),name='cost'),
    path('set/elecricity/billing/plan',views.setBilling,name='billing'),
    path('historical/data',views.historicalData,name='historical data'),
    path('delete/historical/data/<int:id>',views.deleteHistoricalData,name='delete data'),
    path('add/historical/data',addHistoricalData.as_view(),name='add historical data'),
    path('edit/historical/data/<int:id>',editHistoricalData.as_view(),name='edit data'),
    path('data/analyzer',views.analyzer,name='analyzer'),
    path('add/room',views.addRoom,name='add room'),
    #icdc rooms
    path('icdc/rooms',views.icdcRooms,name='icdc rooms'),
    path('edit/icdc/room/<int:id>',editRoom.as_view(),name='edit room'),
    path('delete/room/<int:id>',views.deleteRoom,name='delete room'),
    path('manage/cost/calculator',views.calculatorPage,name='calculator page'),
    path('delete/item/calculator/<int:id>',views.deleteCalculator,name='delete calculator'),
    path('edit/item/data/<int:id>',editCalculator.as_view(),name='edit calculator'),
]

panel/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver
from .utils import send_email
import random
from installation.models import SiteModel
from .tokens import create_token
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
import jsonfield
from channels.layers import get_channel_layer
import json
from asgiref.sync import async_to_sync
from ckeditor_uploader.fields import RichTextUploadingField
from installation.models import SiteModel
from django.utils.crypto import get_random_string
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models import Max
from django.utils.translation import gettext_lazy as _
import environ
from django.contrib.humanize.templatetags.humanize import intcomma,naturaltime
import timeago,datetime
env=environ.Env()
environ.Env.read_env()

     
#generate random
def generate_id():
    return get_random_string(6,'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKMNOPQRSTUVWXYZ0123456789')


#generate random
def generate_serial():
    return get_random_string(12,'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKMNOPQRSTUVWXYZ0123456789')


@receiver(post_save, sender=SiteModel)
def send_installation_email(sender, instance, created, **kwargs):
    if created:
        if instance.is_installed:
            #site is installed
            obj=SiteModel.objects.all()[0]
            subject='Congragulations:Site installed successfully.'
            email=instance.user.email
            message={
                        'user':instance.user,
                        'site_name':instance.site_name,
                        'site_url':instance.site_url,
                        'address':instance.address,
                        'location':instance.location,
                        'description':obj.description,
                        'phone':obj.phone
                     } 
            template='emails/installation.html'
            send_email(subject,email,message,template)





def bgcolor():
    hex_digits=['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']
    digit_array=[]
    for i in range(6):
        digits=hex_digits[random.randint(0,15)]
        digit_array.append(digits)
    joined_digits=''.join(digit_array)
    color='#'+joined_digits
    return color





options=[
            ('---Select gender---',
                    (
                        ('Male','Male'),
                        ('Female','Female'),
                        ('Other','Other'),
                    )
            ),
        ]
class ExtendedAuthUser(models.Model):
    user=models.OneToOneField(User,primary_key=True,on_delete=models.CASCADE)
    phone=PhoneNumberField(null=True,blank=True,verbose_name='phone',unique=True,max_length=13)
    initials=models.CharField(max_length=10,blank=True,null=True)
    category=models.CharField(max_length=100,blank=True,null=True)
    serial_no=models.CharField(max_length=100,default=get_random_string,null=True,blank=True)
    bgcolor=models.CharField(max_length=10,blank=True,null=True,default=bgcolor)
    company=models.CharField(max_length=100,null=True,blank=True,default=env('SITE_NAME'))
    zipcode=models.CharField(max_length=100,null=True,blank=True,default='416')
    city=models.CharField(max_length=100,null=True,blank=True,default='Nairobi')
    country=models.CharField(max_length=100,null=True,blank=True,default='Kenya')
    timezone=models.CharField(max_length=200,null=True,blank=True,default='Africa/Nairobi')
    profile_pic=models.ImageField(upload_to='profiles/',null=True,blank=True,default="placeholder.jpg")
    role=models.CharField(choices=[('employee','Employee'),('admins','Admin'),],max_length=200,null=True,blank=True)
    bio=models.TextField(null=True,blank=True,default='something about you...')
    nickname=models.CharField(max_length=100,null=True,blank=True,default='Your nickname')
    facebook=models.CharField(max_length=200,null=True,blank=True,default='https://facebook.com/username')
    twitter=models.CharField(max_length=200,null=True,blank=True,default='https://twitter.com/username')
    instagram=models.CharField(max_length=200,null=True,blank=True,default='https://instagram.com/username')
    linkedin=models.CharField(max_length=200,null=True,blank=True,default='https://linkedin.com/username')
    gender=models.CharField(choices=options,max_length=6,null=True,blank=True)
    birthday=models.DateField(null=True,blank=True)
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='extended_auth_user'
        verbose_name_plural='extended_auth_users'
    def __str__(self)->str:
        return f'{self.user.username} extended auth profile'

    def delete(self, using=None,keep_parents=False):
        if self.essay or self.profile_pic or self.certificate:
            self.essay.storage.delete(self.essay.name)
            self.profile_pic.storage.delete(self.profile_pic.name)
            self.certificate.storage.delete(self.certificate.name)
        super().delete()


class MeterModel(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=100,blank=True,null=True)
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='meter_tbl'
        verbose_name_plural='meter_tbl'
    def __str__(self)->str:
        return f'{self.user.username} meter info'
    def __unicode__(self):
        return self.name


class EquipmentModel(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=100,blank=True,null=True)
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='equipment_tbl'
        verbose_name_plural='equipment_tbl'
    def __str__(self)->str:
        return f'{self.user.username} equipment info'
    def __unicode__(self):
        return self.name


class RoomModel(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=100,blank=True,null=True)
    operating_condition=models.FloatField(blank=True,null=True)
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='room_tbl'
        verbose_name_plural='room_tbl'
    def __str__(self)->str:
        return f'{self.user.username} room info'
    def __unicode__(self):
        return self.name

class ReadingModel(models.Model):
    parent=models.ForeignKey(MeterModel,on_delete=models.CASCADE)
    cost=models.FloatField(blank=True,null=True)
    datapoint=models.CharField(max_length=100,blank=True,null=True)
    category=models.CharField(max_length=100,blank=True,null=True)
    consumption=models.FloatField(blank=True,null=True)
    meter_location=models.CharField(max_length=100,blank=True,null=True)
    meter_reading=models.FloatField(blank=True,null=True)
    date=models.DateField(blank=True,null=True)
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='meter_readings_tbl'
        verbose_name_plural='meter_readings_tbl'
    def __str__(self)->str:
        return f'{self.category} meter reading info'
    def __unicode__(self):
        return self.category

class CostModel(models.Model):
    parent=models.ForeignKey(RoomModel,on_delete=models.CASCADE)
    datapoint=models.CharField(max_length=100,blank=True,null=True)
    room=models.CharField(max_length=100,blank=True,null=True)
    equipment=models.CharField(max_length=100,blank=True,null=True)
    consumption=models.FloatField(blank=True,null=True)
    category=models.CharField(max_length=100,blank=True,null=True)
    room=models.CharField(max_length=100,blank=True,null=True)
    no_of_hours_used=models.IntegerField(blank=True,null=True)
    quantity=models.IntegerField(blank=True,null=True)
    total_cost=models.FloatField(blank=True,null=True)
    rating=models.FloatField(blank=True,null=True)
    created_on=models.DateTimeField(default=now)
    class Meta:
        db_table='cost_tbl'
        verbose_name_plural='cost_tbl'
    def __str__(self)->str:
        return f'{self.user.username} cost info'

templates/panel/add_historical_data.html
{% extends 'panel/main.html' %}
{% load static %}
{% load humanize %}
{% block body %}
<div class="section-body">
    <div class="container-fluid">
        <div class="row clearfix">
            <nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <ol class="breadcrumb" style="background-color:transparent!important;">
                                <li class="breadcrumb-item"><a class="fg-theme" href="{% url 'dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item"><a class="fg-theme" href="{% url 'historical data' %}">Historical Data</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->
        </div>
        <div class="row clearfix">
            <div class="col-md-6 col-12 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{% if edit %} {{title}}{% else %} {{title}} {% endif %}</h3>
                        <div class="card-options">
                            <a href="javascript:void(0);" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                            <a href="javascript:void(0);" class="card-options-fullscreen" data-toggle="card-fullscreen"><i class="fe fe-maximize"></i></a>
                        </div>
                    </div>
                    <div class="card-body">
                        <form class="ActiveForm" action="#" method="post" novalidate>
	                    	{% csrf_token %}
	                        <div class="form-style-w3ls">
	                        	<div class="form-group">
	                                <label for="">Select meter reading category</label>
	                                {{form.category}}
	                                <div class="feedback"></div>
	                            </div>
	                            <div class="form-group">
	                                <label for=""class="changer">Date</label>
	                                {{form.date}}
	                                <div class="feedback"></div>
	                            </div>
	                            <div class="form-group">
	                              	<select class="form-control" name="meter_name" data-width="100%">
		                                <option value="" selected disabled>Select meter number*</option>
		                                {% for item in meters %}
			                                <option value="{{item.pk}}">{{item.name}}</option>
			                            {% empty %}
		                                	<option value="" disabled="">No meter(s) found</option>
		                                {% endfor %}
		                            </select>
		                            <div class="feedback"></div>
	                            </div>
	                            <div class="form-group">
	                            	<label for="">Meter location</label>
	                            	{{form.meter_location}}
	                            	<div class="feedback"></div>
	                            </div>
	                            <div class="form-group">
	                            	<label for="">Meter reading(kWh)</label>
	                            	{{form.meter_reading}}
	                            	<div class="feedback"></div>
	                            </div>
	                            <button class="btn btn-style btn-primary btn-round w-100"> Submit</button>
	                        </div>
	                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/panel/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="copyright" content="Legit Crew, https://www.devme.com/">
    <title>{% if obj.site_name %} {{obj.site_name}}  {% else %} {{site_name}} {% endif %} | {{title}}</title>
    <meta name="description" content="{{obj.description}}">
    <meta name="author" content="{{designer_name}}">
    <meta name="theme-color" content="{{obj.theme_color}}">
    <meta name="msapplication-navbutton-color" content="{{obj.theme_color}}">
    <meta name="apple-mobile-web-app-status-bar-style" content="{{obj.theme_color}}">
    <meta name="keywords" content="{{obj.key_words}}">
    <meta property="og:site_name" content="{{obj.site_name}}">
    <meta property="og:url" content="{{obj.site_url}}">
    <meta http-equiv="Content-type" content="text/html;charset:utf-8">
    <meta property="og:type" content="website"> 
    <meta property="og:type" content="website"> 
    <meta property="twitter:site" content="https://twitter.com/Kevin36285655">
    <meta property="twitter:title" content="@Kevin36285655">
    <meta property="twitter:image" content="https://twitter.com/Kevin36285655/photo">
    <meta property="twitter:description" content="Life's Simple.">
    <meta property="twitter:text:title" content="Life's Simple.">
    <meta property="og:title" content="{{obj.site_name}} | {{title}}">
    <meta property="og:locale" content="en_US">
    <meta property="og:description" content="{{obj.description}}">
    <meta property="og:image" content="{{obj.favicon.url}}">
    <meta name="apple-mobile-web-app-title" content="{{obj.site_name}}">
    <meta name="application-name" content="{{obj.site_name}}">
    <meta name="msapplication-TileColor" content="{{obj.theme_color}}">
    <meta name="msapplication-config" content="{% static 'manager/assets/images/logos/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">
    <link rel="canonical" href="{{request.get_full_path}}" />
    <meta name="robots" content="index, follow" />
    <meta name="googlebot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
    <meta name="bingbot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
    <link rel="shortcut icon" href="{{obj.favicon.url}}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'panel/assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'panel/assets/css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'panel/assets/css/custom2.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'panel/assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'manager/assets/css/font-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'panel/assets/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'panel/assets/plugins/charts-c3/c3.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'panel/assets/css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'panel/assets/css/theme1.css' %}"/>
    <style type="text/css">
   .seperator 
   {
      float: left;
      width: 100%;
      border-top: 1px solid #ccc;
      text-align: center;
      margin: 50px 0 0;
    }
    .seperator b 
    {
      width: 40px;
      height: 40px;
      font-size: 16px;
      text-align: center;
      line-height: 40px;
      background: #fff;
      display: inline-block;
      border: 1px solid #e0e0e0;
      border-radius: 50%;
      position: relative;
      top: -22px;
      z-index: 1;
    }
    .social-icon 
    {
        width: 100%;
        font-size: 20px;
        padding-top: 20px;
        color: #fff;
        text-align: center;
        float: left;
    }
    .social-icon a 
    {
        font-size: 20px;
        color: white;
        height:80px;
        width:80px;
        margin: 0px 10px;
        padding:10px 10px;
        border: none;
        cursor: pointer;
        text-align:center;
    }
    .google
    {
        background:#ea4335;
    } 
    .google:hover
    {
        border:1px solid #ea4335;
        color:#ea4335;
        background:#fff;
    } 
    .twitter
    {
        background:#00acee;
    } 
    .twitter:hover
    {
        border:1px solid #00acee;
        color:#00acee;
        background:#fff;
    }
    .instagram
    {
        background:#3f729b;
    } 
    .instagram:hover
    {
        border:1px solid #3f729b;
        color:#3f729b;
        background:#fff;
    }
    </style>
</head>
<body class="font-montserrat">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader"></div>
    </div>
    <div id="main_content">

        {% block body %}
        {% endblock %}
        <!-- small model -->
        <div id="myModal" class="modal fade small-model">
            <div class="modal-dialog modal-confirm">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="icon-box">
                            <i class="fa fa-check"></i>
                        </div>              
                        <h4 class="modal-title w-100"></h4> 
                    </div>
                    <div class="modal-body">
                        <p class="text-center"></p>
                    </div>
                   <div class="row">
                        <div class="col-12 text-center">
                            <button class="btn btn-success btn-block btn-round" data-dismiss="modal">OK</button>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
        <!-- //small model -->
    </div>
    <div class="row">
        <div class="col-md-5 col-12 mx-auto cookie-container" style="z-index:9999;">
            <p>We use cookie in this website to give you the best experience on our site and show you relevant ads.To find out more, read our  <a class="page-refresher" href="#">privacy policy</a> and <a class="page-refresher" href="">terms and conditions</a></p>
            <div class="mt-2 text-center">
                <button class="btn cookieBtn">ok</button>
            </div>
        </div>
    </div>
    {{ id|json_script:"userid" }}
    {{ room_name|json_script:"room-name" }}
    <script src="{% static 'panel/assets/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'panel/assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'panel/assets/js/custom.js' %}"></script>
    <script src="{% static 'panel/assets/bundles/lib.vendor.bundle.js' %}"></script>
    <script src="{% static 'panel/assets/bundles/apexcharts.bundle.js' %}"></script>
    <script src="{% static 'panel/assets/bundles/counterup.bundle.js' %}"></script>
    <script src="{% static 'panel/assets/bundles/c3.bundle.js' %}"></script>
    <script src="{% static 'panel/assets/js/core.js' %}"></script>
    <script src="{% static 'panel/assets/js/page/project-index.js' %}"></script>
</body>
</html>

templates/panel/edit_calculator_page.html
{% extends 'panel/main.html' %}
{% load static %}
{% load humanize %}
{% block body %}
<div class="section-body">
    <div class="container-fluid">
        <div class="row clearfix">
            <nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <ol class="breadcrumb" style="background-color:transparent!important;">
                                <li class="breadcrumb-item"><a class="fg-theme" href="{% url 'dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item"><a class="fg-theme" href="{% url 'historical data' %}">Historical Data</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->
        </div>
        <div class="row clearfix">
            <div class="col-md-6 col-12 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{% if edit %} {{title}}{% else %} {{title}} {% endif %}</h3>
                        <div class="card-options">
                            <a href="javascript:void(0);" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                            <a href="javascript:void(0);" class="card-options-fullscreen" data-toggle="card-fullscreen"><i class="fe fe-maximize"></i></a>
                        </div>
                    </div>
                    <div class="card-body">
                       	<form action="#" method="post" class="ActiveForm" novalidate>
	                        <h5 class="mb-4 text-center"><b>Equipment details</b></h5>
	                        {% csrf_token %}
	                        <div class="form-style-w3ls">
	                            <div class="form-group">
	                                <label for="">Select category</label>
	                                {{form.category}}
	                                <div class="feedback"></div>
	                            </div>
	                            <div class="form-group">
	                                <label for=""class="changer">Date</label>
	                                {{form.date}}
	                                <div class="feedback"></div>
	                            </div>
	                            <div class="form-group">
	                                <label for="">Room name</label>
	                                <select name="room" id="id_room" class="form-control">
	                                    {% for room in rooms %}
	                                    <option value="{{room.id}}">{{room.name}}</option>
	                                    {% empty %}
	                                    <option value="" selected="" disabled="">No room found</option>
	                                    {% endfor %}
	                                </select>
	                                <div class="feedback"></div>
	                            </div> 
	                            <div class="form-group">
	                                <label for="">Equipment</label>
	                                <select name="equipment" id="id_equipment" class="form-control">
	                                    {% for equipment in equipments %}
	                                    <option value="{{equipment.name}}">{{equipment.name}}</option>
	                                    {% empty %}
	                                    <option value="" selected="" disabled="">No equipment found</option>
	                                    {% endfor %}
	                                </select>
	                                <div class="feedback"></div>
	                            </div> 
	                            <div class="form-group">
	                                <label for="">Rating(W)</label>
	                                {{form.rating}}
	                                <div class="feedback"></div>
	                            </div>
	                            <div class="form-group">
	                                <label for="">Quantity</label>
	                                {{form.quantity}}
	                                <div class="feedback"></div>
	                            </div>
	                            <div class="form-group">
	                                <label for="">No of hours used</label>
	                                {{form.no_of_hours_used}}
	                                <div class="feedback"></div>
	                            </div>
	                            <button class="btn btn-style btn-primary btn-round w-100"> Submit</button>
	                        </div>
	                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/panel/edit_equipment.html
{% extends 'panel/main.html' %}
{% load static %}
{% load humanize %}
{% block body %}
<div class="section-body">
    <div class="container-fluid">
        <div class="row clearfix">
            <nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <ol class="breadcrumb" style="background-color:transparent!important;">
                                <li class="breadcrumb-item"><a class="fg-theme" href="{% url 'dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item"><a class="fg-theme" href="{% url 'meters' %}">Meters</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->
        </div>
        <div class="row clearfix">
            <div class="col-md-5 col-12 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title text-truncate">{% if edit %} {{title}}{% endif %}</h3>
                        <div class="card-options">
                            <a href="javascript:void(0);" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                            <a href="javascript:void(0);" class="card-options-fullscreen" data-toggle="card-fullscreen"><i class="fe fe-maximize"></i></a>
                        </div>
                    </div>
                    <div class="card-body">
                        <form class="ActiveForm" method="post" novalidate>
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Equipment name</label>
                                {{form.name}}
                                <div class="feedback"></div>
                            </div>
                            <div class="col-sm-12 text-center m-t-20">
                                <button class="btn btn-primary btn-round"><i class="ti-save"></i> SAVE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}